
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * Class Tugas1Kripto
 */

public class BackupKriptoTugas2 extends javax.swing.JFrame {

    private static File input = null;
    private static File output = null;
    private static File key = null;
    private static File tweak = null;
    private static XTSAES xts;

    private static javax.swing.JButton buttonEncrypt,buttonDecrypt;
    private static javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;

    private static javax.swing.JTextField inputTextField, keyTextField, tweakTextField, outputTextField;

    /**
     * Creates new form GUI
     */
    public BackupKriptoTugas2(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        //text field
        inputTextField = new javax.swing.JTextField();
        keyTextField = new javax.swing.JTextField();
        tweakTextField = new javax.swing.JTextField();
        outputTextField = new javax.swing.JTextField();


        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        //button
        buttonEncrypt = new javax.swing.JButton();
        buttonDecrypt = new javax.swing.JButton();

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("XTS-AES");

        inputTextField.setText("input path");
        inputTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt){
                inputTextFieldMouseClicked(evt);
            }
        });
        // inputTextField.addActionListener(new java.awt.event.ActionListener() {
        //     public void actionPerformed(java.awt.event.ActionEvent evt) {
        //         inputTextFieldActionPerformed(evt);
        //     }
        // });

        keyTextField.setText("key path");
        keyTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt){
                keyTextFieldMouseClicked(evt);
            }
        });

        tweakTextField.setText("tweak path");
        tweakTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tweakTextFieldMouseClicked(evt);
            }
        });

        outputTextField.setText("output path");
        outputTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                outputTextFieldMouseClicked(evt);
            }
        });

        buttonEncrypt.setText("Encrypt");
        buttonEncrypt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEncryptMouseClicked(evt);
            }
        });

        buttonDecrypt.setText("Decrypt");
        buttonDecrypt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDecryptMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(keyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tweakTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    // .addGroup(layout.createSequentialGroup()
                    //     .addGap(157, 157, 157)
                    //     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    //         .addComponent(jButton1)
                    //         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    //             .addComponent(jRadioButton2)
                    //             .addComponent(jRadioButton1))))
                                )
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(inputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(buttonEncrypt)
                .addGap(40, 40, 40)
                .addComponent(buttonDecrypt)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void inputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTextFieldActionPerformed

    private void inputTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickedEvent
        int res = jFileChooser1.showOpenDialog(this);
        if (res == JFileChooser.APPROVE_OPTION) {
            input = jFileChooser1.getSelectedFile();
            inputTextField.setText(input.getAbsolutePath());
        }
    }//GEN-LAST:event_mouseClickedEvent

    private void tweakTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keyTextFieldMouseClicked
        int res = jFileChooser1.showOpenDialog(this);
        if (res == JFileChooser.APPROVE_OPTION) {
            tweak = jFileChooser1.getSelectedFile();
            tweakTextField.setText(tweak.getAbsolutePath());
        }
    }//GEN-LAST:event_keyTextFieldMouseClicked

    private void keyTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keyTextFieldMouseClicked
        int res = jFileChooser1.showOpenDialog(this);
        if (res == JFileChooser.APPROVE_OPTION) {
            key = jFileChooser1.getSelectedFile();
            keyTextField.setText(key.getAbsolutePath());
        }
    }//GEN-LAST:event_keyTextFieldMouseClicked

    private void outputTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outputTextFieldMouseClicked
        int res = jFileChooser1.showSaveDialog(this);
        if (res == JFileChooser.APPROVE_OPTION) {
            output = jFileChooser1.getSelectedFile();
            outputTextField.setText(output.getAbsolutePath());
        }
    }//GEN-LAST:event_outputTextFieldMouseClicked

    private void buttonEncryptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST
      boolean valid = isValidData();
      if (valid) {
        if(tweak == null){
          xts = new XTSAES(input, key, output);
        }else{
          xts = new XTSAES(input, key, tweak, output);
        }
        xts.encrypt();
      }
    }//GEN-LAST:event_jButton1MouseClicked

    private void buttonDecryptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST
        boolean valid = isValidData();
        if (valid) {
          if(tweak == null){
            xts = new XTSAES(input, key, output);
          }else{
            xts = new XTSAES(input, key, tweak, output);
          }
        xts.decrypt();
      }
    }//GEN-LAST:event_jButton1MouseClicked


    public boolean isValidData(){
      if (input == null) {
          JOptionPane.showMessageDialog(this, "Pilih input", "Error!",
                  JOptionPane.ERROR_MESSAGE);
                  return false;
      } else if (key == null) {
          JOptionPane.showMessageDialog(this, "Pilih key", "Error!",
                  JOptionPane.ERROR_MESSAGE);
                  return false;
      } else if (output == null) {
          JOptionPane.showMessageDialog(this, "Pilih output", "Error!",
                  JOptionPane.ERROR_MESSAGE);
                  return false;
      }
      return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas1Kripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas1Kripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas1Kripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas1Kripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BackupKriptoTugas2().setVisible(true);

            }
        });

    }
}
